### ISSUE TITLE
Consider adding special support for YouTube URLs

### ISSUE THREAD

**Issue by joestump** [Hydrophobefireman/reader#1]
Or possibly even yt-dlp? I notice there's a caching argument in one of the Docker files. Would be neat to use yt-dlp with basically any video URL. 

Just spent a few minutes creating a FreshRSS extension that uses this. It's a nice enhancement!

**Comment by Hydrophobefireman** [comment]
Good idea, not sure if it's in the scope for this project as an alternative YouTube fronted is a massive undertaking in its own. 
I don't know what would be the minimal functionality to implement to make it be usable.
I'd suggest something like [metube](https://github.com/alexta69/metube) to be a good alternative or invidious

**Comment by joestump** [comment]
@Hydrophobefireman I ended up forking this and updating it to support oEmbed along with a bunch of other features like dark/light mode: https://github.com/joestump/reader

**Comment by Hydrophobefireman** [comment]
looks awesome!
